# Generated by Django 6.0.4 on 2026-07-19 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_alter_project_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="milestone",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="milestones",
                to="projects.project",
            ),
        ),
    ]
